#! /bin/sh

lualatex example
lualatex example
mv example.pdf preview.pdf
pdftoppm preview.pdf preview -jpeg -singlefile -r 42

lualatex example_tikz
lualatex example_tikz
mv example_tikz.pdf preview_tikz.pdf
pdftoppm preview_tikz.pdf preview_tikz -jpeg -singlefile -r 42
